# Generated by Django 5.1.3 on 2024-11-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etkinlik_adi', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('sure', models.DurationField()),
                ('konum', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kullanici_adi', models.CharField(max_length=50, unique=True)),
                ('sifre', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('konum', models.CharField(blank=True, max_length=100, null=True)),
                ('ilgi_alanlari', models.TextField(blank=True, null=True)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('cinsiyet', models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın'), ('D', 'Diğer')], max_length=10, null=True)),
                ('telefon_no', models.CharField(blank=True, max_length=15, null=True)),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='profil_fotograflari/')),
            ],
        ),
        migrations.CreateModel(
            name='Katilimci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.etkinlik')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesaj_metni', models.TextField()),
                ('gonderim_zamani', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_mesajlar', to='backend.kullanici')),
                ('gonderici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to='backend.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='Puan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.PositiveIntegerField()),
                ('kazanilan_tarih', models.DateField()),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.kullanici')),
            ],
        ),
    ]
