# Generated by Django 5.1.3 on 2024-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_etkinlik_sure_etkinlik_etkinlik_suresi'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='konum_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='konum_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='etkinlik_suresi',
            field=models.DurationField(),
        ),
    ]
