# Generated by Django 5.1.3 on 2024-11-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_etkinlik_konum_lat_etkinlik_konum_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etkinlik',
            name='konum_lat',
        ),
        migrations.RemoveField(
            model_name='etkinlik',
            name='konum_lng',
        ),
    ]
