# Generated by Django 5.1.3 on 2024-11-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_etkinlik_konum_latitude_etkinlik_konum_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='konum_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='konum_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
