# Generated by Django 5.1.3 on 2024-11-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_etkinlik_konum_latitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='katilimci',
            unique_together={('kullanici', 'etkinlik')},
        ),
    ]
