# Generated by Django 5.1.3 on 2024-11-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_katilimci_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='katilimci',
            unique_together={('kullanici', 'etkinlik')},
        ),
    ]
