# Generated by Django 5.1.3 on 2024-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_katilimci_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='kategori',
            field=models.TextField(max_length=50),
        ),
    ]
