# Generated by Django 5.1.3 on 2024-11-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_etkinlik_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='etkinlik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='backend.etkinlik'),
            preserve_default=False,
        ),
    ]
