# Generated by Django 5.1.3 on 2024-11-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_mesaj_etkinlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='kategori',
            field=models.CharField(choices=[('spor', 'Spor'), ('muzik', 'Müzik'), ('resim', 'Resim')], max_length=50),
        ),
    ]
