# Generated by Django 5.1.3 on 2024-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_etkinlik_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnayBekleyenEtkinlikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_adi', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('sure', models.IntegerField()),
                ('kategori', models.CharField(max_length=255)),
                ('konum', models.CharField(max_length=255)),
                ('konum_latitude', models.FloatField()),
                ('konum_longitude', models.FloatField()),
                ('kullanici_id', models.IntegerField()),
            ],
        ),
    ]
