# Generated by Django 5.1.3 on 2024-12-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_onaybekleyenetkinlikler'),
    ]

    operations = [
        migrations.AddField(
            model_name='onaybekleyenetkinlikler',
            name='onaylanmis',
            field=models.BooleanField(default=False),
        ),
    ]
