# Generated by Django 5.1.3 on 2024-12-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_onaybekleyenetkinlikler_onaylanmis'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='kullanici',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='backend.kullanici'),
            preserve_default=False,
        ),
    ]
