# Generated by Django 5.1.3 on 2024-12-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_etkinlik_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='kategori',
            field=models.CharField(choices=[('spor', 'Spor'), ('muzik', 'Müzik'), ('resim', 'Resim'), ('tiyatro', 'Tiyatro'), ('sinema', 'Sinema'), ('dans', 'Dans'), ('edebiyat', 'Edebiyat'), ('yemek', 'Yemek'), ('teknoloji', 'Teknoloji'), ('seminer', 'Seminer'), ('konser', 'Konser'), ('festivaller', 'Festivaller'), ('konferans', 'Konferans')], max_length=50),
        ),
    ]
